In [40]:
import pandas as pd
# 获取数据集
data = pd.read_csv('titanic/titanic.csv')
data.head()

,row.names,pclass,survived,name,age,embarked,home.dest,room,ticket,boat,sex
0,1,1st,1,"Allen, Miss Elisabeth Walton",29.0000,Southampton,"St Louis, MO",B-5,24160 L221,2,female
1,2,1st,0,"Allison, Miss Helen Loraine",2.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,NaN,female
2,3,1st,0,"Allison, Mr Hudson Joshua Creighton",30.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,(135),male
3,4,1st,0,"Allison, Mrs Hudson J.C. (Bessie Waldo Daniels)",25.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,NaN,female
4,5,1st,1,"Allison, Master Hudson Trevor",0.9167,Southampton,"Montreal, PQ / Chesterville, ON",C22,NaN,11,male

In [41]:
# 获得特征值 和 目标值
x = data[['pclass','age','sex']]
y = data['survived']

In [42]:
# 数据处理
# 缺失值处理
x['age'].fillna(x['age'].mean(), inplace=True)

/var/folders/b3/szc09tk96s97zm3zkfrdgjc80000gn/T/ipykernel_10654/4133524303.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x['age'].fillna(x['age'].mean(), inplace=True)
/var/folders/b3/szc09tk96s97zm3zkfrdgjc80000gn/T/ipykernel_10654/4133524303.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['age'].fillna(x['age'].mean(), inplace=True)

In [43]:
# 数据集划分
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=22)
x_train

    pclass        age     sex
100    1st  19.000000    male
195    1st  28.000000    male
263    1st  17.000000    male
880    3rd  31.194181  female
910    3rd  31.194181    male
..     ...        ...     ...
356    2nd  26.000000    male
960    3rd  31.194181    male
812    3rd  31.194181    male
132    1st  36.000000  female
885    3rd  31.194181    male

[984 rows x 3 columns]

In [44]:
# 特征工程 - 字典特征提取
from sklearn.feature_extraction import DictVectorizer
x_train = x_train.to_dict(orient="records")
x_test = x_test.to_dict(orient="records")
transfer = DictVectorizer()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [45]:
# 决策树预测
from sklearn.tree import DecisionTreeClassifier

estimator = DecisionTreeClassifier(criterion="entropy")
estimator.fit(x_train, y_train)

y_predict = estimator.predict(x_test)

In [46]:
y_predict==y_test

831      True
261     False
1210     True
1155     True
255      True
        ...
1146     True
1125    False
386      True
1025    False
337      True
Name: survived, Length: 329, dtype: bool

In [47]:
print(estimator.score(x_test,y_test))

0.7811550151975684

In [48]:
# 随机森林预测
# 随机森林
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
# 网格搜索
grid_param = {"n_estimators":[100,200,400,600,800,1000,1200],"max_depth":[3,10,15,25]}
estimator = RandomForestClassifier()
estimator = GridSearchCV(estimator,param_grid=grid_param,cv=3)
estimator.fit(x_train, y_train)
y_predict = estimator.predict(x_test) 
print('结果:\n', y_test == y_predict)
print('准确率为\n',estimator.score(x_test, y_test))
print('最佳参数\n',estimator.best_params_)
print('最佳结果',estimator.best_score_)
print('最佳估计器\n',estimator.best_estimator_)
print('最佳交叉验证结果\n',estimator.cv_results_)

结果:
 831      True
261      True
1210     True
1155     True
255      True
        ...
1146     True
1125    False
386      True
1025    False
337      True
Name: survived, Length: 329, dtype: bool
准确率为
 0.7811550151975684
最佳参数
 {'max_depth': 3, 'n_estimators': 800}
最佳结果 0.8414634146341463
最佳估计器
 RandomForestClassifier(max_depth=3, n_estimators=800)
最佳交叉验证结果
 {'mean_fit_time': array([0.05033708, 0.09007359, 0.1758426 , 0.27117085, 0.38358863,
       0.43740082, 0.54181719, 0.0588309 , 0.11902563, 0.22523975,
       0.36686826, 0.46272413, 0.59448981, 0.692518  , 0.05951015,
       0.13363298, 0.23400259, 0.33937724, 0.47315502, 0.56075064,
       0.70556601, 0.05669745, 0.11497092, 0.22856331, 0.34318161,
       0.4713943 , 0.58158731, 0.68683362]), 'std_fit_time': array([0.00462289, 0.00284952, 0.00164555, 0.00271867, 0.04345152,
       0.00529977, 0.01097718, 0.00060817, 0.00497369, 0.0047667 ,
       0.02468176, 0.00643057, 0.0148084 , 0.01178525, 0.00390985,
       0.01748771, 0.00286864, 0.01172384, 0.01426065, 0.01489215,
       0.04245423, 0.00089103, 0.00115535, 0.01013317, 0.00829073,
       0.01559042, 0.01942293, 0.02315375]), 'mean_score_time': array([0.00257158, 0.00421206, 0.00799799, 0.01155432, 0.01519744,
       0.01922075, 0.02301351, 0.00310914, 0.00563979, 0.01020598,
       0.01529328, 0.02103511, 0.02508163, 0.02985692, 0.0029002 ,
       0.00565807, 0.01040475, 0.01511216, 0.0217909 , 0.02498651,
       0.02967803, 0.00287064, 0.00551081, 0.01031168, 0.01543307,
       0.02015169, 0.02481143, 0.03078731]), 'std_score_time': array([1.16576202e-04, 7.54170221e-05, 6.24674877e-05, 6.13936971e-05,
       2.07737647e-04, 2.11518028e-04, 3.41714093e-04, 1.98286330e-04,
       1.62530256e-04, 3.33162873e-04, 3.64342144e-04, 1.47909304e-03,
       4.68048766e-04, 1.06045089e-04, 1.87350419e-05, 4.29960408e-04,
       1.42521983e-04, 2.74586240e-04, 2.40028683e-03, 3.73092143e-04,
       4.01733977e-04, 3.82290064e-05, 1.26058887e-04, 1.22213084e-04,
       2.19127385e-04, 3.05133827e-04, 2.72284897e-04, 1.67865662e-03]), 'param_max_depth': masked_array(data=[3, 3, 3, 3, 3, 3, 3, 10, 10, 10, 10, 10, 10, 10, 15,
                   15, 15, 15, 15, 15, 15, 25, 25, 25, 25, 25, 25, 25],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'param_n_estimators': masked_array(data=[100, 200, 400, 600, 800, 1000, 1200, 100, 200, 400,
                   600, 800, 1000, 1200, 100, 200, 400, 600, 800, 1000,
                   1200, 100, 200, 400, 600, 800, 1000, 1200],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'params': [{'max_depth': 3, 'n_estimators': 100}, {'max_depth': 3, 'n_estimators': 200}, {'max_depth': 3, 'n_estimators': 400}, {'max_depth': 3, 'n_estimators': 600}, {'max_depth': 3, 'n_estimators': 800}, {'max_depth': 3, 'n_estimators': 1000}, {'max_depth': 3, 'n_estimators': 1200}, {'max_depth': 10, 'n_estimators': 100}, {'max_depth': 10, 'n_estimators': 200}, {'max_depth': 10, 'n_estimators': 400}, {'max_depth': 10, 'n_estimators': 600}, {'max_depth': 10, 'n_estimators': 800}, {'max_depth': 10, 'n_estimators': 1000}, {'max_depth': 10, 'n_estimators': 1200}, {'max_depth': 15, 'n_estimators': 100}, {'max_depth': 15, 'n_estimators': 200}, {'max_depth': 15, 'n_estimators': 400}, {'max_depth': 15, 'n_estimators': 600}, {'max_depth': 15, 'n_estimators': 800}, {'max_depth': 15, 'n_estimators': 1000}, {'max_depth': 15, 'n_estimators': 1200}, {'max_depth': 25, 'n_estimators': 100}, {'max_depth': 25, 'n_estimators': 200}, {'max_depth': 25, 'n_estimators': 400}, {'max_depth': 25, 'n_estimators': 600}, {'max_depth': 25, 'n_estimators': 800}, {'max_depth': 25, 'n_estimators': 1000}, {'max_depth': 25, 'n_estimators': 1200}], 'split0_test_score': array([0.83841463, 0.83231707, 0.83841463, 0.83841463, 0.83841463,
       0.83841463, 0.83841463, 0.79573171, 0.79878049, 0.79878049,
       0.79573171, 0.79268293, 0.79268293, 0.79268293, 0.80182927,
       0.79878049, 0.79268293, 0.79268293, 0.79573171, 0.79573171,
       0.79268293, 0.80182927, 0.79268293, 0.79268293, 0.79878049,
       0.79268293, 0.79573171, 0.79573171]), 'split1_test_score': array([0.85670732, 0.85670732, 0.85670732, 0.85670732, 0.85670732,
       0.85670732, 0.85670732, 0.85060976, 0.85060976, 0.85060976,
       0.85670732, 0.84756098, 0.85365854, 0.85365854, 0.85060976,
       0.84756098, 0.84756098, 0.85365854, 0.85670732, 0.85060976,
       0.84756098, 0.84146341, 0.84756098, 0.8445122 , 0.85365854,
       0.85060976, 0.85670732, 0.85060976]), 'split2_test_score': array([0.82621951, 0.83231707, 0.82621951, 0.82621951, 0.82926829,
       0.82621951, 0.82621951, 0.80182927, 0.80487805, 0.80182927,
       0.80182927, 0.80182927, 0.80487805, 0.80182927, 0.80182927,
       0.80182927, 0.80182927, 0.80182927, 0.80182927, 0.80182927,
       0.80487805, 0.80487805, 0.80487805, 0.80182927, 0.80182927,
       0.80182927, 0.80487805, 0.80487805]), 'mean_test_score': array([0.84044715, 0.84044715, 0.84044715, 0.84044715, 0.84146341,
       0.84044715, 0.84044715, 0.81605691, 0.81808943, 0.81707317,
       0.81808943, 0.81402439, 0.81707317, 0.81605691, 0.81808943,
       0.81605691, 0.81402439, 0.81605691, 0.81808943, 0.81605691,
       0.81504065, 0.81605691, 0.81504065, 0.81300813, 0.81808943,
       0.81504065, 0.81910569, 0.81707317]), 'std_test_score': array([0.0125293 , 0.01149767, 0.0125293 , 0.0125293 , 0.01140749,
       0.0125293 , 0.0125293 , 0.02455904, 0.02312969, 0.02374659,
       0.0274202 , 0.02400612, 0.02634447, 0.02684928, 0.02299534,
       0.02231148, 0.02400612, 0.02684928, 0.0274202 , 0.02455904,
       0.02352812, 0.01800818, 0.02352812, 0.02258751, 0.02518193,
       0.02542682, 0.02684928, 0.02400612]), 'rank_test_score': array([ 2,  2,  2,  2,  1,  2,  2, 17,  9, 14,  9, 26, 14, 17,  9, 17, 26,
       17,  9, 17, 23, 17, 23, 28,  9, 23,  8, 14], dtype=int32)}

In [ ]:
# 逻辑回归
from sklearn.